### ISSUE TITLE
Question regarding converting LAMMP data file and dump file to config.Z1

### ISSUE THREAD

**Issue by peter-zhang-chem** [mkmat/Z1plus-code#1]
Dear MK,

I have a LAMMPS data file and a LAMMPs dump file that I'd like to convert to config.Z1 file for analysis. However, inputting the dump file directly in Z1+ program resulted in crashing. I tried to use the script available in the repo to extract the backbone and generate the config.Z1 file; however, I got no output.

Here I attached the test files [here.](https://drive.google.com/file/d/1LOgJvSlRfXwo2-9vY83T5ckSznNNWdaj/view?usp=drive_link) Can you please give me a couple of pointers of how to generate the correct input for the Z1+ program? Thanks!

**Comment by peter-zhang-chem** [comment]
Following up on my question, I was able to use `Z1+import-lammps.pl` to generate a `config.Z1` file.

**Comment by mkmat** [comment]
Dear Peter (if I may),


Thanks for your message. It seems you solved your problem. I didn't download the

files you sent, but do you know what caused your problem? I would then add

this information to the github site.


Eventually, your dump file had unsorted IDs or Z1+ was not able to

recognize the chains as this information is only contained in the data file?


All the best, Martin


--

Martin Kröger
Prof Computational Polymer Physics, PD Dr habil
website www.complexfluids.ethz.ch<http://www.complexfluids.ethz.ch>

Swiss Federal Institute of Technology, ETH Zurich
Leopold-Ruzicka-Weg 4, HCP F 48.2, CH-8093 ZURICH, Switzerland phone +41-44-632-6622 fax -1076

Google Scholar EUCO-BAAAAAJ ORCID 0000-0003-1402-6714 Scopus 56416643300


________________________________

**Comment by peter-zhang-chem** [comment]
Hey! 

Thank you for the timely response. I will have to look into the `extract-backbone.pl` script for to see what might be the issue. I input the same `.data` and `dump` file for the `extract-backbone.pl` and `Z1+import-lammps.pl` - and `extract-backbone.pl` was not able to run correctly to output the `config.Z1` file. Right now I am trying to analyzing/understand the output I got from the analysis - so I will get back to you at a later time regarding what might have happened with the `extract-backbone.pl`.

Thanks!

Peter

**Comment by mkmat** [comment]
Dear Peter,


Let me know if I should have a look at your files.

Probably it is about the formatting of data and dump

files and it could be sufficient if you post the first 10

lines of a dump file and the part of the data file

until the say 20th line after 'Atoms' by email.


Greetings, Martin


--

Martin Kröger
Prof Computational Polymer Physics, PD Dr habil
website www.complexfluids.ethz.ch<http://www.complexfluids.ethz.ch>

Swiss Federal Institute of Technology, ETH Zurich
Leopold-Ruzicka-Weg 4, HCP F 48.2, CH-8093 ZURICH, Switzerland phone +41-44-632-6622 fax -1076

Google Scholar EUCO-BAAAAAJ ORCID 0000-0003-1402-6714 Scopus 56416643300


________________________________

**Comment by peter-zhang-chem** [comment]
Dear Martin,

Ok, that'd be great! 

Here is beginning portion of the data file:
```
LAMMPS data file. CGCMM style. atom_style full generated by VMD/TopoTools v1.7 on Thu Apr 04 11:43:30 EDT 2024
 9024 atoms
 8960 bonds
 0 angles
 0 dihedrals
 0 impropers
 3 atom types
 1 bond types
 0 angle types
 0 dihedral types
 0 improper types
 -381.353540 1118.646460  xlo xhi
 -325.649424 1174.350576  ylo yhi
 -344.678904 1155.321096  zlo zhi

# Pair Coeffs
#
# 1  A
# 2  C
# 3  G

# Bond Coeffs
#
# 1  

 Masses

 1 39.948002 # A
 2 12.010700 # C
 3 69.723000 # G

 Atoms # full

1 1 2 0.000000 103.589508 164.201080 471.432495 # C CYT
2 2 1 0.000000 102.579193 158.147980 471.438110 # A ADE
3 3 3 0.000000 102.035980 153.521759 474.633545 # G GUA
4 4 2 0.000000 102.872406 151.734192 480.493103 # C CYT
5 5 1 0.000000 102.498383 147.463348 484.110962 # A ADE
6 6 3 0.000000 101.344696 143.881531 488.439941 # G GUA
7 7 2 0.000000 102.650482 139.132507 490.965698 # C CYT
8 8 1 0.000000 106.925201 139.131836 495.002686 # A ADE
9 9 3 0.000000 111.695648 141.219269 498.194336 # G GUA
10 10 2 0.000000 116.481354 140.336823 501.122437 # C CYT
11 11 1 0.000000 121.827545 137.300018 500.431091 # A ADE
12 12 3 0.000000 126.666168 134.139893 502.225952 # G GUA
13 13 2 0.000000 130.583771 130.122253 503.335876 # C CYT
14 14 1 0.000000 129.694427 124.575012 502.921265 # A ADE
15 15 3 0.000000 131.787445 119.330780 502.795776 # G GUA
16 16 2 0.000000 134.016510 114.287109 500.142273 # C CYT
17 17 1 0.000000 139.271881 111.263916 499.137024 # A ADE
18 18 3 0.000000 144.555756 109.422485 500.863159 # G GUA
19 19 2 0.000000 146.606049 106.436554 505.548035 # C CYT
20 20 1 0.000000 144.243561 105.940399 510.782593 # A ADE
```

and here is the beginning portion of the dump file:

```
ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
9024
ITEM: BOX BOUNDS pp pp pp
-381.354 1118.65
-325.334 1174.67
-344.769 1155.23
ITEM: ATOMS id type xu yu zu
 1 1 103.59 164.201 471.432
```

**Comment by mkmat** [comment]
Dear Peter,


I must admit, I am only reading the email but did not have a look at my code, but

here is what I see from the email as possible problems:


data-file:

Atoms with a preceding blank, usually there is no blank before Atoms. Same for Masses and Bonds.

The # C CYT after the coordinates, I do not remember if I interpreted these columns as ix iy iz

because usually, the data file has id mol type q x y z ix iy iz while you have ix iy iz replaced by

some arbitrary text. Finally, what is the 2nd column in the Atoms section? Is it mol and

has each atom its own mol ID?


1 1 2 0.000000 103.589508 164.201080 471.432495 # C CYT

2 2 1 0.000000 102.579193 158.147980 471.438110 # A ADE


dump-file:

Most likely the problem is here, there is no "mol" in the dump-file.

ITEM: ATOMS id type xu yu zu


I agree, that the bond information is in the data file so that in principle a code

can retrieve this information from the data file and then use it to interpret the dump

file. Has you data file also a Bonds section?


If so, then I can give it try and please send me your data file and the first two

snapshots of your dump trajectory. I could write a code to handle your relatively

unconventional data and dump files. Were they generated by lammps?


All the best, Martin

--

Martin Kröger
Prof Computational Polymer Physics, PD Dr habil
website www.complexfluids.ethz.ch<http://www.complexfluids.ethz.ch>

Swiss Federal Institute of Technology, ETH Zurich
Leopold-Ruzicka-Weg 4, HCP F 48.2, CH-8093 ZURICH, Switzerland phone +41-44-632-6622 fax -1076

Google Scholar EUCO-BAAAAAJ ORCID 0000-0003-1402-6714 Scopus 56416643300


________________________________

**Comment by peter-zhang-chem** [comment]
Dear Martin,

Hey sorry for the belated response. 

1. Regarding the data file:
The atoms in data file has the following format:
```  
1 molecule-tag atom-type q x y z nx ny nz  (nx,ny,nz are optional -
  ...                                    see "true flag" input command)
  ...                
  N molecule-tag atom-type q x y z nx ny nz  (N = # of atoms)
```
Yea, the space before atoms, masses, and bonds is weird - I generated these files from VMD.

2. Yes, I have a Bonds section in the `.data` file.

3. Thank you so much for your time - I have attached the `.data` file and the `dump` file with first 2 frames here.
[dump-data-files.zip](https://github.com/mkmat/Z1plus-code/files/15012544/dump-data-files.zip)

**Comment by mkmat** [comment]
Dear Peter,


Sorry for the late response. Let me check your data file first.

I just do not remember if Z1+ returns a lammps data file for the

primitive network or not. Such lammps data file you can visualize

using vmd or ovito, for example. I usually use matlab for myself,

but the blender figures were done by Clarisse Luap, I forwarded

your message. Using matlab (or r) you can in any case read

directly the Z1-formatted files and visualize them quite easily.

It should even be not be difficult using python and matplotlib.

If I find time I could try to set up a python script. Let me know if

Clarisse does not respond and if you have any of the mentioned

softwares. Until later,


Martin


--

Martin Kröger
Prof Computational Polymer Physics, PD Dr habil
website www.complexfluids.ethz.ch<http://www.complexfluids.ethz.ch>

Swiss Federal Institute of Technology, ETH Zurich
Leopold-Ruzicka-Weg 4, HCP F 48.2, CH-8093 ZURICH, Switzerland phone +41-44-632-6622 fax -1076

Google Scholar EUCO-BAAAAAJ ORCID 0000-0003-1402-6714 Scopus 56416643300


________________________________

**Comment by peter-zhang-chem** [comment]
Dear Martin,

Thank you. I do not think Z1+ returns a lammps data file. Here are the list of files I got from Z1+ output.

- config.Z1
- Lpp_values.dat
- N_values.dat
- Ree_values.dat
- Z1+initconfig.dat
- Z1+SP.dat
- Z1+summary.dat
- Z1+summary.html
- Z_values.dat

I have all the programs you mentioned - currently I am using python to plot values of my interest from the `Z1+summary.dat` file. It would be awesome to visualize the primitive network used by Z1+ to calculate these values.

And thank you so much, I will wait to see if Clarisse Luap gets back to me.

Peter

**Comment by mkmat** [comment]
Dear Peter,


I see. So then I will eventually also write a script that creates a lammps data file

from the Z1+SP.dat file, which contains the primitive path network. I will think

about it and let you know. Please ask back in a few days!


All the best, Martin


--

Martin Kröger
Prof Computational Polymer Physics, PD Dr habil
website www.complexfluids.ethz.ch<http://www.complexfluids.ethz.ch>

Swiss Federal Institute of Technology, ETH Zurich
Leopold-Ruzicka-Weg 4, HCP F 48.2, CH-8093 ZURICH, Switzerland phone +41-44-632-6622 fax -1076

Google Scholar EUCO-BAAAAAJ ORCID 0000-0003-1402-6714 Scopus 56416643300


________________________________

**Comment by peter-zhang-chem** [comment]
Thank you so much for your time and this really useful program, Martin! I will check back with you in a few days!

**Comment by peter-zhang-chem** [comment]
Dear Martin,

I hope you are well. Just wanted to check in with you regarding the script for creating lammps data file from the Z1+SP.dat file.

Thank you!

Peter

**Comment by mkmat** [comment]
Dear Peter,


Thanks for your message. I thought I answered already. Is what is written on the Z1+ github

https://github.com/mkmat/Z1plus-code


not what you are looking for? Please let me know, I forgot everything in the meantime ..


Martin


[cid:80e06dd2-b770-4bc5-872e-89a4ee9aaf84]



--

Martin Kröger
Prof Computational Polymer Physics, PD Dr habil
website www.complexfluids.ethz.ch<http://www.complexfluids.ethz.ch>

Swiss Federal Institute of Technology, ETH Zurich
Leopold-Ruzicka-Weg 4, HCP F 48.2, CH-8093 ZURICH, Switzerland phone +41-44-632-6622 fax -1076

Google Scholar EUCO-BAAAAAJ ORCID 0000-0003-1402-6714 Scopus 56416643300


________________________________

**Comment by peter-zhang-chem** [comment]
Hey Martin,

Thank you! I was able to visualize the shortest path configuration in vmd using the `Z1+SP-to-data.pl`.

Peter
